### ISSUE TITLE
test_year_2020.py が Fail する

### ISSUE THREAD

**Issue by sig9org** [Lalcs/jpholiday#7]
jpholiday を利用させて頂いております。 必要になる都度、祝日判定処理を自前で実装していたのですが、ライブラリ化して頂いているので大変、助かっております (作者の方に感謝いたします)。 オンラインのカレンダー情報を利用するライブラリを見かけたのですが、接続先の影響 (URL 変更やフォーマット変更) を受けてしまう為、「ローカルのみで動作する」という方針も有り難いです。

a08df7a80adcb1e13a0e7e0c7f70370a10b1ffcf でユニットテストを実行したところ、Fail するようです。 他の年のユニットテストも Fail するようなのですが、他の方の環境ですとテスト結果は如何でしょうか？

```sh
# python -m unittest tests/test_year_2020.py
FFF
======================================================================
FAIL: test_count_month (tests.test_year_2020.TestYear2020)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jpholiday/tests/test_year_2020.py", line 36, in test_count_month
    self.assertEqual(len(jpholiday.month_holidays(2020, 1)), 2)
AssertionError: 0 != 2

======================================================================
FAIL: test_count_year (tests.test_year_2020.TestYear2020)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jpholiday/tests/test_year_2020.py", line 53, in test_count_year
    self.assertEqual(len(jpholiday.year_holidays(2020)), 18)
AssertionError: 0 != 18

======================================================================
FAIL: test_holiday (tests.test_year_2020.TestYear2020)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/jpholiday/tests/test_year_2020.py", line 13, in test_holiday
    self.assertEqual(jpholiday.is_holiday_name(datetime.date(2020, 1, 1)), '元日')
AssertionError: None != '元日'

----------------------------------------------------------------------
Ran 3 tests in 0.005s

FAILED (failures=3)
```

**Comment by Lalcs** [comment]
ご連絡ありがとうございます。
こちらでも事象確認できましたのでv0.1.1にて修正いたしました。

ご確認ください。

**Comment by sig9org** [comment]
v0.1.1 で修正されていることを確認しました。 ご対応、有難うございました。

```sh
$ python -m unittest tests/test_year_2020.py
...
----------------------------------------------------------------------
Ran 3 tests in 0.243s

OK
```
